branches: 
  - main
repositoryUrl: https://github.com/liatrio//image-builder-gitty-up.git
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
